name: flutter_in_the_dark

packages:
  - apps/**

command:
  bootstrap:
    environment:
      sdk: ">=3.5.0 <4.0.0"
    dependencies:
      ff_card:
        git:
          url: https://github.com/lohnn/flutter_and_friends_speaker_cards.git
          path: ff_card
      flutter:
        sdk: flutter
      flutter_hooks: ^0.21.1-pre.4
    dev_dependencies:
      flutter_lints: ^4.0.0
      flutter_test:
        sdk: flutter

scripts:
  build_web:
    run: melos exec -- flutter build web
  fix:
    run: melos exec -- dart fix --apply
  upgrade:
    run: melos exec -- flutter pub upgrade
    description: Upgrade to the latest supported versions of all packages.
